### ISSUE TITLE
请问后续是否能够增加 IPv6 地址的数据？

### ISSUE THREAD

**Issue by cherinyy** [mayaxcn/china-ip-list#4]
目前 IPv6 的可用性逐渐提高，希望能够增加 IPv6 地址的数据。

**Comment by mayaxcn** [comment]
> 

明天有空的时候 我试试更新一下支持ipv6的代码

**Comment by mayaxcn** [comment]
已更新IPV6的数据

**Comment by cherinyy** [comment]
辛苦了，不过似乎数据不太全面？

比如 [240e::/20](https://bgp.he.net/net/240e::/20) 并不在列表中。

**Comment by mayaxcn** [comment]
> 辛苦了，不过似乎数据不太全面？
> 
> 比如 [240e::/20](https://bgp.he.net/net/240e::/20) 并不在列表中。

我看到列表中包含了以下子网：
240e::/104
240e:100::/104
240e:200::/105
240e:400::/106
240e:800::/107
240e:1000::/108
240e:2000::/109

你说的240e::/20是否包含在以上子网内

**Comment by cherinyy** [comment]
> 你说的240e::/20是否包含在以上子网内

240e::/20 包含上述子网，而不是反过来。

比如 240e:97d:2000:c0e::30/128 显然不在列表目前包含的子网当中。

可参考 [IPv6 CIDR blocks - Classless Inter-Domain Routing -  Wikipedia](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#IPv6_CIDR_blocks)

**Comment by mayaxcn** [comment]
> > 你说的240e::/20是否包含在以上子网内
> 
> 240e::/20 包含上述子网，而不是反过来。
> 
> 比如 240e:97d:2000:c0e::30/128 显然不在列表目前包含的子网当中。
> 
> 可参考 [IPv6 CIDR blocks - Classless Inter-Domain Routing - Wikipedia](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#IPv6_CIDR_blocks)

不好意思，我对IPV6子网这块的计算还不是理解得很透彻，请问https://github.com/mayaxcn/china-ip-list/blob/master/chn_ip_v6.txt 这个列表的数据是否没有缺失？？

**Comment by cherinyy** [comment]
> 请问https://github.com/mayaxcn/china-ip-list/blob/master/chn_ip_v6.txt 这个列表的数据是否没有缺失？

这个也是缺失的，因为它也不包含 `240e:97d::` 等地址。

**Comment by mayaxcn** [comment]
我刚更新了代码，现在的https://github.com/mayaxcn/china-ip-list/blob/master/chnroute_v6.txt 是包含240e::/24 这部分

**Comment by cherinyy** [comment]
这样应该没什么大问题了，以后看看还有没有人来反馈吧，辛苦了❤️

**Comment by mayaxcn** [comment]
我把chn_ip_v6.txt也更新了一下，现在的IP范围应该是完整的了
